# create your drupal and postgres config here, based off the last assignment
version: '3.9'

services:
  drupal:
    build: .
    image: custom-drupal
    ports:
      - '8080:80'
    volumes:
      - type: volume
        source: drupal-modules
        target: /var/www/html/modules
      - type: volume
        source: drupal-profiles
        target: /var/www/html/profiles
      - type: volume
        source: drupal-themes
        target: /var/www/html/themes

  postgres:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - type: volume
        source: drupal-db
        target: /var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-db:
